version: '3.8'

services:
  # api-service:
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./.env:/app/.env
  #   environment:
  #     SPRING_PROFILES_ACTIVE: prod
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres-db
  #     SPRING_DATASOURCE_USERNAME: dbusr
  #     SPRING_DATASOURCE_PASSWORD: dbpass
  #     SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
  #     # Actualizado para que la API se comunique con MinIO dentro de la red de Docker
  #     MINIO_ENDPOINT: http://minio:9000 
  #     MINIO_ACCESS-KEY: minioadmin
  #     MINIO_SECRET-KEY: minioadmin
  #   depends_on:
  #     - db
  #     - minio # Añadida dependencia de MinIO

  db:
    image: postgres:16-alpine
    container_name: colabora-db
    environment:
      POSTGRES_DB: postgres-db
      POSTGRES_USER: dbusr
      POSTGRES_PASSWORD: dbpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Nuevo servicio para MinIO
  minio:
    image: quay.io/minio/minio
    container_name: colabora-minio
    ports:
      - "9000:9000" # Puerto de la API de MinIO
      - "9001:9001" # Puerto de la consola de MinIO
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: miniopass
    volumes:
      - miniodata:/data
    command: server /data --console-address ":9001"

volumes:
  pgdata:
  miniodata: # Volumen para persistir los datos de MinIO
