spring.application.name=agora
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/colabora}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:pass}
spring.datasource.driver-class-name=org.postgresql.Driver
server.servlet.context-path=/api
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=false

spring.security.user.name=${SPRING_SECURITY_USER_NAME}
spring.security.user.password=${SPRING_SECURITY_USER_PASSWORD}

security.jwt.user.generator=${SECURITY.JWT.USER.GENERATOR}
security.jwt.key.private=${SECURITY.JWT.KEY.PRIVATE}


minio.endpoint=${MINIO_ENDPOINT:http://localhost:9000}
minio.access-key=${MINIO_ACCESS-KEY:minioadmin}
minio.secret-key=${MINIO_SECRET-KEY:minioadmin}
minio.bucket-name=user-images

orcid.client-id=${ORCID_CLIENT_ID}
orcid.client-secret=${ORCID_CLIENT_SECRET}
orcid.redirect-uri=${ORCID_REDIRECT_URI}
