package com.agora.auth.model;

public enum RoleEnum {
    ACADEMICO, // VER_RECOMENDACIONES, BUSCAR_USUARIO, CONTACTAR_USUARIO, VER_EVENTOS, AGREGAR_EVENTO, EDITAR_EVENTO, ELIMINAR_EVENTO, VER_PERFIL, EDITAR_PERFIL, ELIMINAR_PERFIL, VER_NOTIFICACIONES
    COMUNICADOR, // VER_RECOMENDACIONES, BUSCAR_USUARIO, CONTACTAR_USUARIO, VER_PERFIL, EDITAR_PERFIL, ELIMINAR_PERFIL, VER_NOTIFICACIONES
    ADMIN // Acceso completo a todos los endpoints administrativos
}
